### ISSUE TITLE
Intention Concept

### ISSUE THREAD

**Issue by mjreich** [nxus/core#10]
Intentions are to requests what Promises are to responses, e.g. I have an intention to fulfill/process a request.

The main value behind intentions is they allow us to control flow and asynchronous process requests in the same declarative way as promises.

### Intention(cb)
Create a new intention with the callable to be executed when the intention is triggered.

```
new Intention((...args) => {
  return this._myMethod(...args)
});
```
or more simply

```
new Intention(this._myMethod.bind(this));
```

### Intention.before(handler)
Set a handler which will receive the arguments of the intention, and do something on them. The return of the handler (either a value or Promise) is passed to the next before() handler serially after the return is resolved.

@returns the Intention
```
app.get('router').provide('route').before((route, handler) => {route = "/prefix"+route; return [route, handler]}) 
```

### Intention.with(args...)
Triggering processing of the intention with the provided args.

@returns A promise for the result

```
app.get('router').provide('route').with("/", _myHandler); 
```

### Intention.after(handler)
Receive the result and do something. Return of the handler (either a value or Promise) is passed to the next after() handler serially after the return is resolved.
```
app.get('router').request('renderedText').after((text) => {return 'some new text'+text;}) 
```

### Exceptions
If any of the before/after handlers throw an exception, it is passed to the return Promise of `with()`

## Module implementation
```
Module.send = (name) => {
  return this._intentions[name]
}
```
Or more specifically
```
Module.send = (name) => {
  return this._sendIntentions[name]
}
```

**Comment by loppear** [comment]
See if I'm reading this right:
Renderer:
` app.get('renderer').respond('render').with((type, text) => { return Promise... })`

ModuleMonkeyingWithRenderer:
` app.get('renderer').respond('render').before((...args) => { return args })`
` app.get('renderer').respond('render').after((text) => {return text})`

NeedsRendering:
` app.get('renderer').request('render').with(type, text).then(...)`

(and mutatis mutandis for provide/gather, but probably `.gather('route').each` not `with` , or `.gather('route').with((routes) => routes.each(...)` ?)

**Comment by loppear** [comment]
Why not just use keep using Dispatcher's events-with-promises for this? `respond('name').with(handler)` maps to `on('name', handler)`, before and after are added to Dispatcher as convenience for name+'.before' etc, and `request('name').with(args)` is the alias for `emit` from #9. Gets rid of the handling in Module you're going for, doesn't introduce a new concept. Only alteration to my code above would be that before and after aren't as if Monkeyer were calling respond, instead

` app.get('renderer').before('render', handler)` etc.

**Comment by mjreich** [comment]
@loppear a couple of thoughts (may be right/wrong on these...)

1. the current on/emit handlers don't support waterfall/serial processing of before/after handlers, so we have to implement that somewhere.  I think there's probably a lot of jimmying we'll have to do if we use event.before/event.after events rather than just do something like async.waterfall.  This can either live in the dispatcher, or somewhere else (e.g. the Intentions class).
2. if we go your route, then I don't think there's any reason to have 'with()' any more, as it doesn't do anything and we should just use `request('name', someArg, anotherArg) for consistency.
3. I'm not sure request/respond and provide/gather are aliases for on/emit.  Maybe, but not sure yet.

**Comment by loppear** [comment]
1, that's a bug in our current emit I agree, but applies to all uses of before/after. which I think should be part of the Dispatcher directly.
2, yes totally ready to kill with :)
3, they are if we implement request/respond and provide/gather with events rather than re-inventing.

**Comment by mjreich** [comment]
Adding a 4: I think we want to avoid name collisions between on/emit, request/respond, provide/gather - I could imagine where a before/after on one would not make sense on another.  So we would need to namespace events internally as 'send.name' + 'send.name.before' + 'send.name.after'...etc

For example, I could see (semantically) having both `request('route')` and `provide('route')` - should 'before' apply to both, since they conceivable could have different signatures/functionality?

E.g. I'm skeptical its an easy implementation of them all just aliasing on/emit...

**Comment by loppear** [comment]
Nope, namespacing the events in the alias functions is fine by me, agree on not clashing.

**Comment by mjreich** [comment]
Closing this one in favor of #9.
