### ISSUE TITLE
NxusModule methods return empty array in place of undefined when invoked through proxy.

### ISSUE THREAD

**Issue by davidkellerman** [nxus/core#104]
If a NxusModule method returns `undefined` as its result, when it is invoked through the proxy interface, the promise returned through the proxy resolves to an empty array instead of `undefined`.

This code appears to be doing the substitution:
https://github.com/nxus/core/blob/master/src/Dispatcher.js#L128

Am I completely missing some reason this makes sense? Because it seems totally non-obvious that this substitution would take place, and of course any code that expects to be able to check for that _undefined_ result fails...

**Comment by loppear** [comment]
This is definitely a bug, some left over guarding before refactor of squashArrayResults. Adding some tests and removing the offending set.
