### ISSUE TITLE
Module.provide/gather and .request/respond are synonymous

### ISSUE THREAD

**Issue by loppear** [nxus/core#16]
And should be aliases to each other with single implementations.

#### The names are useful for different cases
Linguistically indicating whether the intended recipient is the module or the caller, basically.

#### Differences now (what do these do besides alias `on` and `emit`)
1. `provide` waits to send arguments until after app.load.
  1. This makes it useful as a proxy for sending data during module loading. 
  2. We (implicitly) expect request to only be called after load anyways, so this makes `request` safer.
2. `respond` cleans up response values (lifts a single element array).
  1. We basically never care about the response value of `gather` (though it's available).
  2. But if we did it somewhere would be nice if it were clean too.

#### What does this get us?
1. Simpler implementation yet, further safety and syntax benefits for both in one place.
2. But most excellently, we get (3) from #15. With a single implementation (and with both expecting to wait until load), we can have Module proxy future registered events as methods, so

  ```
  app.get('renderer').render(type, text);
  app.get('router').route(url, handler)
  ```
work even though one is a `gather` and one is a `respond`.

**Comment by mjreich** [comment]
So what happens when the proxy detects a method being called that doesn't exist?  Or if 'renderer' hasn't been set yet?  Ideally, these would throw a warning, but not an exception.

**Comment by mjreich** [comment]
But otherwise, definitely :+1:

**Comment by loppear** [comment]
The Module-as-Proxy should catch that missing method and translate it to a `provide` call. No error or warning, just the desired "do this once we've all loaded" behavior of `provide` today.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy (https://github.com/samshull/node-proxy e.g. as here https://github.com/geta6/node-methodmissing which is a fine implementation of this specific case.)
