### ISSUE TITLE
Mailer Module

### ISSUE THREAD

**Issue by mjreich** [nxus/core#22]
The Mailer module should provide a common API for sending emails from services like SendGrid and Mandril.

## The API should be pretty simple:

1. Provide/gather service.
1. Send Email
  - to - an array of addresses
  - content - the content to display
  - opts - optional args including ccs, bccs, and html/text content

## Open questions:
1. Attachment support in v1?
2. Any other services we want to expose?

**Comment by loppear** [comment]
Er, don't you mean `request/respond` service not `provide/gather`, under the semantics that the latter is "one-time"? Will revisit the suggestion to consolidate/rename these again, since they seem to remain confusing.
