### ISSUE TITLE
Metrics Module

### ISSUE THREAD

**Issue by mjreich** [nxus/core#23]
Should capture arbitrary events through a web API and an internal Waterline Model:

## Model
- eventName, string
- timestamp, datetime
- metadata, JSON (arbitrarily stores whatever you pass with the event)

**Comment by loppear** [comment]
Can we call this "Metrics" or "Happenings" instead?

Should provide a nxus event for collecting these too, rather than having internal use directly need to create model instances? `app.get('happenings').emit('happened', 'userSignup', [{metadata}])`

**Comment by mjreich** [comment]
Missed this comment.  I'm fine with Metrics.  Changing accordingly.
