### ISSUE TITLE
Better handling of before/after events in Dispatcher

### ISSUE THREAD

**Issue by mjreich** [nxus/core#3]
Right now, anything returning in .before and .after is globbed together by Promise.all() in the return to the call of emit.

## Dispatcher.emit() Improvements

**event.before**
Should receive the arguments, and pass the returned onto the next `event.before` listener as the new arguments, waterfall style.

**event** 
Receives the final arguments as processed by `event.before`.

**event.after** 
Receives the return of all `event` handlers as an array.  Returns new values, which is passed to the next `event.after` listener, waterfall style.

The last step is returning the final event.after promise to the emit caller.

**Comment by loppear** [comment]
Proposed as the alternative to #10, also add `.before('event', handler)` and `.after('event', handler)` convenience methods for the event naming convention.

**Comment by loppear** [comment]
Only issue with "waterfall" style here is I'm not sure how you'd define an order on before/after events - but that's probably OK in saying you can't really change the signature of either args or response in before/after - you can modify in place, or extend, or observe, but no guarantees about getting the original raw args or response vs getting another before/after's modifications.

Waterfall with bluebird implementations would be something like
```
return Promise.reduce(beforeHandlers, (prev, current) => { return current(prev) }, args)
  .then((newArgs) => return Promise.all(eventHandlers.map( [... current promising-wrapper func ...])
  .then((results) => return Promise.reduce(afterHandlers, (prev, current) => { return current(prev) }, results);
