### ISSUE TITLE
Add in fixture support for Tester

### ISSUE THREAD

**Issue by mjreich** [nxus/core#32]

**Comment by loppear** [comment]
1. With the separate test application server (where the app and models are available), the easy route would be to support test-suite-wide fixtures.
   * These would load if env==test, the calls for them would be in the application code not in the test code. (Could reasonably go in the module that defines the model, or in separate module (that's loaded in all cases, but only does test things / if env==test.)
   * `app.get('tester').fixture('modelName', 'path/to/file', importOpts)`
   * This is basically the same as providing "starting data" for categories or users etc, so makes implementing both easy.
 1. Alternatively, could have the tester module provide an HTTP API for doing per-test setup/teardown for fixture data, and helper methods for before/after in tests.
   * Fixture calls and files could live with the tests.
   * Perhaps more chance of spurious failure/confusion (though only if something is broken. Application middleware or response mucking impacting these test routes). More moving parts
   * Tests can be more independent - there's not one complete set of test data that all are depending on. Can cleanup after each test usefully.

We can reasonably start with (1), if we feel like that's useful on its own then (2) can be a separate issue for a future milestone.

**Comment by mjreich** [comment]
How about 1 + a convenience folder 'fixtures' where data is loaded based on pluralized model names?

E.g. `/fixtures/cities.csv` would populate the `city` model?

**Comment by loppear** [comment]
As convenience for (1) that sounds fine, yep. As we move to module-contained models, probably won't be the recommended pattern, but hopefully we'll have (2) around then. :)
