### ISSUE TITLE
Change admin-ui/AdminBase to gather config or class path

### ISSUE THREAD

**Issue by mjreich** [nxus/core#45]
The admin-ui module should then require the class

**Comment by loppear** [comment]
Per comments on https://github.com/nxus/admin-ui/pull/2/files I think this should be "gather config options or class", no need to have admin-ui require from a string /unless/ we want to support defining Admin gathers in application config, ala:
```
"config": {
  "admin-ui": {
    "adminModel": [
      ["user", "path/to/UserAdmin"],
      ["todo", {opts}]
    ]
 }
}
```
Might be worth considering for 2.4, as part of #43 (?) to have a general way to set provides via config, e.g. above would be automatically converted to `this.provide('adminModel', "user", "path/to")` etc on startup, for any config keys that match gather names.

**Comment by mjreich** [comment]
@loppear the problem with not accepting a string path is we need the try/catch logic in Users.  Opted to add that as a third option, so you can pass:
1. A model name and options hash
1. A string file path
1. A Class Object

**Comment by mjreich** [comment]
Closing.
