### ISSUE TITLE
Requesters should return promises that fulfill after `load`

### ISSUE THREAD

**Issue by mjreich** [nxus/core#49]
The following returns three `undefined` objects.
```javascript
constructor(app) {
    this.app.get('storage').getModel('user').then((m) => {this.models.user = m})
    this.app.get('storage').getModel('initiative').then((m) => {this.models.initiative = m})
    this.app.get('storage').getModel('metric').then((m) => {this.models.metric = m})
}
```
For it to work as expected, need to wrap in `startup`
```javascript
  this.app.on('startup', () => {
    this.app.get('storage').getModel('user').then((m) => {this.models.user = m})
    this.app.get('storage').getModel('initiative').then((m) => {this.models.initiative = m})
    this.app.get('storage').getModel('metric').then((m) => {this.models.metric = m})
  })
```
Ideally, this should be automated in the same way that gather/provide waits until after load.

**Comment by loppear** [comment]
Hmm. So it already is "in the same way" as gather/provide (load.before, actually), the issue once again is that _everything_ happens then (providing the models and requesting them, in this case).

Of course, specific responders could enforce a later delay (`storage.getModel` could have the `app.on('startup')`) when they have an internal ordering they need to control.

**Comment by loppear** [comment]
Can't have provide and request with different semantics and still have the `storage.model(...); storage.getModel(...)` proxy language BUT could support that responder-side delay universally (`this.respond('getModel')` wraps in load.after) or as an optional argument (`this.respond('getModel', 'startup')`) I think.

**Comment by mjreich** [comment]
I guess I would rather it be module specific then - Storage should only respond to `getModel` after the models have been initialized.  Probably better than a one-size fits all approach.

**Comment by loppear** [comment]
Yeah, let's start there, though I think you may be right that all responders should wait till startup.

**Comment by mjreich** [comment]
Yeah, that's what I was thinking. From a lifecycle standpoint, all `gathers` should be handled at load, and all responders handled at `startup` or maybe `load.after`.  Might be worth making the change and seeing if it works.

**Comment by mjreich** [comment]
And looping back on this one to document our decision.

We are going to leave it up to the implementer to do this right. E.g., storage needs to resolve the promise after the gather phase is completed (after load)

**Comment by mjreich** [comment]
@loppear ok to close this one?
