### ISSUE TITLE
Add `replace` proxy to simplify `provideAfter`

### ISSUE THREAD

**Issue by mjreich** [nxus/core#50]
I think there’s three options:

1. Create a proxy camelCase method:
```
app.get(‘router’).replaceRoute(‘/‘, …)
```
1. Create a standalone method:
```
app.get(‘router’).replace().route(‘/‘, …)
```
1. Create a standalone object (a la should):
```
app.get(‘router’).replace.route(‘/‘, …)
```

**Comment by mjreich** [comment]
I think my preference would 2, as `replace` could be synonymous with `provideAfter` but also returns a proxy handler.  So the base version would be:
```
app.get(‘router’).replace(‘route’, ‘/‘, …)
```
And the proxy return usage would be:
```
app.get(‘router’).replace().route(‘/‘, …)
```

**Comment by loppear** [comment]
Yeah, i think I like `replace().method` best out of those, as a pattern we may want to use for other methods too. (replace is just better name for provideAfter, agreed)

**Comment by mjreich** [comment]
@loppear agreed, and also like the pattern.  You able to put together a PR?

**Comment by loppear** [comment]
Yeah, but further thought: should this really be that common? Modules that are providing default implementations (of routes, templates, etc) should be using `provideBefore` right, so normal users can just use `provide` / the normal proxy method.

is "provideBefore" (with this pattern) a fine term or do we want something else (`original`? `default` is a reserved word, unfortunately, but original/replace seem like a good pair.)

**Comment by mjreich** [comment]
Yeah, I was thinking about that as well.  ProvideBefore works inconsistently right now, so we probably want to test out/explore what changes are required.

That said, I think its good to support both cases.  I think you can use 'default' as an object key, if that helps :)
