### ISSUE TITLE
Consider: namespacing "provide" and "request" events separately

### ISSUE THREAD

**Issue by loppear** [nxus/core#54]
This would allow you to register both a `gather` and a `respond` for the same noun, .e.g `.model(class...)` to set, `.model('identity')` to get.

Big issue is with ProxyMethods (`app.get('storage').model(...)`) as it currently pushes everything to a provide. It is possible to have it dispatch to `provide` before loading and `request` after loading, but this means that you can only `provide` pre-load and only `request` post-load. This may be what we want, but breaks some current tests, and would likely conflict with the intent of #49 (would effectively disallow calling request, via proxy, earlier and expecting it to wait.)

**Comment by mjreich** [comment]
Ok, so where did we end up on this?  Basically that we’re going to leave it up to the implementing class to do the right thing vis a vis verb/noun?  E.g.:

### Storage
`model()` :arrow_right: `setModel()` (gather/provide)
`getModel()` no change (request/respond)

### Router
`route()` :arrow_right: `setRoute()` (gather/provide)

### Templater
`render()` no change (request/respond)

**Comment by loppear** [comment]
Yep, although (my feeling) is we should not recommend both "get and set" prefixes, but that implementors should make the choice about most common usage. That is, I would change Storage to `respond('model').gather('setModel')` and but leave Router as `gather('route')` (not setRoute).

**Comment by mjreich** [comment]
@loppear closable?
