### ISSUE TITLE
WriteDefaultConfig method on Application

### ISSUE THREAD

**Issue by mjreich** [nxus/core#56]
There are cases where a module needs to define default config that should be persisted, especially when initially installing the module:

* Storage: needs to define a default storage adapter/connection and generated DB name.
* Searcher: needs to define a localhost elastic search adapter/connection for dev.

## Proposal
Add a WriteDefaultConfig method on Application that writes the specified config to the package.json file on first load, if not present already.  Also loads into the internal 'config' hash for convenience.

```
const _defaultConfig = {
  connections: {...}
  adapters: {...}
}
app.writeDefaultConfig('storage', _defaultConfig)
```

This gives us a couple of advantages:

1) Auto fills sane defaults into package.json (under dev), reducing potential issues with missing config values, etc.
2) Moves dependencies, like sails-mongo and seabourne/waterline-elasticsearch into the module as a peerDep, rather than requiring the user to manually install it.
3) Streamlines/simplifies the getting started process.

**Comment by mjreich** [comment]
@loppear for discussion today...

**Comment by loppear** [comment]
Only issue I see with having "default" config written into the "application" config on initial load is that you can't upgrade modules and get the new default values. Generate and write a unique database name, versus documenting that you need to pick a database name? That said, fine with improving defaults - what's the dynamic/startup config that searcher needs, or in both these cases are you just talking about writing _defaultConfig as-is?

And I'm still not comfortable with making sails-mongo an always-installed dependency of storage, cause we really need to get ourselves off of always using mongo.

**Comment by mjreich** [comment]
@loppear re: upgrading, the default config is only written if its not already present in the config.  E.g. its written on module install, but never overwrites an existing config.  

As for generating a db name, I think there's plenty of examples of that in the wild (`heroku create` is one  example).  It simplifies the generator need down the road, and we're already doing it for the admin user.

As for mongo - fine, but let's pick a default (postgres?) and go with it.  My need here is somewhat self-serving - I have yet to actually define a storage adapter that is different than the default (mongo), and I'm largely copying and pasting from config in previous projects.  That's exactly what i want to avoid with all of this.  Feedback from scott was consistent with this as well.

**Comment by loppear** [comment]
Yeah, that was my concern with upgrading, you won't get to write changed values for defaultConfig that the user hasn't actually overridden (and so would want to keep using the now-changed default when upgrading).

I'm totally fine with a tool/template generating values and writing these bits out there (including auto-installing sails-mongo for the starting app), just uncomfortable with it being in the core storage module startup (if we pick postgres, then you have to be able to build postgres adapters even if you intend to use mongo, and vice versa).
