### ISSUE TITLE
Config (from package.json) should extend config from dev to test and production

### ISSUE THREAD

**Issue by loppear** [nxus/core#61]
So that production config is only values that are different from the default dev config.

``` config = _.deepExtend({}, config.dev, config[this.getNodeEnv()]) ```

**Comment by mjreich** [comment]
I would instead have the config values in the root of the `config` object extend into a env config:

```
config: {
  siteName: “Test site”,
  dev: {
    connections: {…}
    …
  },
  production: {
    connections: {…}
    ...
  }
}
```

**Comment by loppear** [comment]
:+1:
