### ISSUE TITLE
Dispatcher appears to need an "on" handler in order for "after" handlers to work properly

### ISSUE THREAD

**Issue by ScottMaxson** [nxus/core#73]
Based on recent experience working with data-loader - there was some (broken) code in data-loader to set up default handlers for the "model.<model-id>" and "models.<model-id>" events. In working through this, it appears that a handler attached to model.<model-id>.after receives an empty argument list if there is no handler for the model.<model-id>

This necessitates other modules setting up default "do nothing but return the arguments" handlers for everything to work.

See comments at https://github.com/nxus/data-loader/pull/6 for some background.

**Comment by mjreich** [comment]
@loppear I wonder if your fix to the underlying boot issue fixed this?
