### ISSUE TITLE
Proposal: chainable module method returns (the PromiseProxy)

### ISSUE THREAD

**Issue by mjreich** [nxus/core#89]
Going off of @davidkellerman’s comment about chaining in modules methods. 

May be too crazy - its late 😄 

## Current approach
```javascript
var mymodule = app.get('mymodule')
mymodule.doSomething('myVar')
mymodule.getSomething('myVar').then((result) => {…})
```

## Proposal
provide/ModuleProxy now returns a PromiseProxy that either:

1) Calls the called method after the `startup` event if it exists on the callee scope.
2) If its a `then` passes through to the underlying promise as is.

```javascript
import {mymodule} from 'MyModule'

mymodule
  .doSomething('myVar') // PromiseProxy -> MyModule.doSomething -> PromiseProxy
  .getSomething('myVar') // PromiseProxy -> MyModule.getSomething  -> PromiseProxy
  .then((result) => {…}) // PromiseProxy -> Promise.then -> Promise
```

But would not work as:

```javascript
import {mymodule} from 'MyModule'

mymodule
  .getSomething('myVar') // PromiseProxy -> MyModule.getSomething -> PromiseProxy
  .then((result) => {…}) // PromiseProxy -> Promise.then -> Promise
  .doSomething('myVar') // Exception
```

**Comment by mjreich** [comment]
👍 for reducing redundant lines of code
👎 for being a new paradigm and breaking the 'everything is a promise' rule of returns in Nxus. (Becomes everything is the module or a promise, depending on what you last called).

**Comment by loppear** [comment]
Would need to allow more than just `.then`, rest of promise API (`.spread` etc) too. Realistically this would be a Proxy of both Promise and Module, with all the downsides of reasoning about merged namespaces.

**Comment by mjreich** [comment]
Yeah, agree.  A _cute_ trick, but probably more confusing than helpful ;)

**Comment by ScottMaxson** [comment]
FWIW I'm lukewarm about this.
