### ISSUE TITLE
Rethinking Design Patterns

### ISSUE THREAD

**Issue by mjreich** [nxus/core#9]
Within Nxus, we should have three main patterns for interacting with modules.

## Events
Used for exchanging notifications of something happening.

The standard `on()`/`emit()` methods from EventEmitter.  

**Note**: For consistency, it may be worth returning the Intention described in #10 

## Provide/Gather
Used for sending data to another module(s) asynchronously, with no need for arguments/input from the receiving module, and no expectation of a return value.

Use Case: I want to provide a route to the Router.

### Module.provide(name, ...args)
@param string name The name of the value to provide
@param ...args Any arguments to pass to the Gather

@example
```
app.use('router').provide('route', '/', this._handler.bind(this));
```

### Module.gather(name)
@param string name The name of the value to gather
@param callable handler The handler for each provided value

@example
```
app.use('router').gather('route', this._setRoute.bind(this) )
```

## Request/Respond
Used for getting data from another module(s) asynchronously, with the ability to send arguments/input as part of the request, and I expect a return value.

Use Case: I want to get a rendered piece of text.

### Module.request(name, ...args)
@param string name The name of the value to request
@param ...args Any arguments to the request

@example
```
app.get('renderer').request('renderedText', 'ejs', 'my text to render');
```

### Module.respond(name, handler)
@param string name The name of the value to respond with
@param callable handler The handler to return [a Promise of] the requested value

@example
```
app.get('renderer').respond('renderedText', (type, content) => { return new Promise(...)})
```

**Comment by loppear** [comment]
:+1: to these names.

**Comment by loppear** [comment]
1. Gather should still be delayed till app `load.after`, right?
2. Should the signature of gather change to emit each provided value separately? That is, gather is just a delayed `on()`, the handler for gather receives individual args?
