### ISSUE TITLE
[M]VC helper module

### ISSUE THREAD

**Issue by mjreich** [nxus/core#90]
We do a lot of simple MVC style parts of applications.  Rather than writing all the connections between models, views, routes and controller logic, it would be nice to have a helper module base class that automates/reduces the code.

```javascript
import {MVCModule} from 'nxus-mvc'

class Thing extends MVCModule {
  constructor(opts) {
    super(opts)
  }

  index(req, res) {
    return {some, opts} // simple object return that is passed to the view
  }

  view(req, res) {
    return this.models.Thing.find().then((things) => {
      return {things}
    })
  }

  edit(req, res) {
    return this.models.Thing.findOne(req.params.id).then((thing) => {
      return {thing}
    })
  }
}
```

This would expect the following folder structure with models and templates

```
-index.js
-models/
  |-thing.js
-templates/
  |-index.ejs
  |-view.ejs
  |-edit.ejs
```

The following routes would automatically be created.  The root is the lowercased, singularized `constructor.name`

```
GET /thing
GET /thing/:id
GET /thing/:id/edit

PUT /thing
POST /thing/:id
DELETE /thing/:id
```

**Comment by loppear** [comment]
Would this relate to / be a better extension or support for `BaseUI.viewModel`?

**Comment by mjreich** [comment]
@loppear yep, good call.  This should probably be what `ViewModel` is in 4.0 - that way even the view templates are provided and overridable.  I’ll move it over to @nxus/base-ui.
